name: Publish to pub.dev
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
permissions:
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      - name: Install dependencies
        run: flutter pub get
      - name: Run unit tests
        run: flutter test
      - name: Publish package
        run: flutter pub publish --force